version: "3.7"
services:
  impacct-db-service:
    image: postgres:11.2
    container_name: impacct-db-container
    restart: on-failure
    environment:
      POSTGRES_DB: "impacct-db"
      POSTGRES_USER: "myImpacctDbUser"
      POSTGRES_PASSWORD: "myImpacctDbPassword"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h impacct-db -p 5432 -U myImpacctDbUser" ]
      interval: 10s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "impacct-db-volume:/var/lib/mysql"
    networks:
      - impacct-network
  impacct-service:
    container_name: impacct-container
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - impacct-db-service
    command: sh -c './wait-for impacct-db-service:5432 -- npm start'
    networks:
      - impacct-network
networks:
  impacct-network:
    driver: bridge
volumes:
  impacct-db-volume: { }