server:
  port: 8080
okta:
  oauth2:
    issuer: https://dev-62601352.okta.com/oauth2/default
    client-id: 0oa4xn4jrZecZ3ryw5d6
    client-secret: o4-aWkNoStzQvNa4xJmb64p3s6vcVJP6nwgaU3xe
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://impacct-db-service:5432/impacct-db
    name: impacct-db
    username: myImpacctDbUser
    password: myImpacctDbPassword
    driver-class-name: org.postgresql.Driver
    tomcat:
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      # remove annoying but harmless startUp invocationTargetException : null
      temp.use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true